[package]
name = "blockchain_sui"
version = "0.0.1"
edition = "2024"

[addresses]
blockchain_sui = "0x0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }